### ISSUE TITLE
No output when using mod

### ISSUE THREAD

**Issue by davidthehat** [Jaffe2718/Fabric-Microphone-Text-Input#5]
As far as I can tell, I have installed and configured the mod properly. The model's path is the correct absolute path, and the model is detected in game. When I press the keybind, it says "Recording and Recognizing" but then nothing happens.

I have two questions. First, am I supposed to hold the button while talking? Or just press it then talk?

Secondly, how can I figure out what's going wrong? I think java has access to my mic, but I don't know how to test it. I see in my windows settings that java is using my mic. Do I just have to wait longer?

**Comment by Jaffe2718** [comment]
Speech recognition is implemented using the AI algorithm provided by the Vosk API, which has a relatively low operating efficiency. Generally, a delay of 3-5 seconds is required after the user finishes speaking before there is a response. Of course, the first time the game is started, it may be slower, perhaps more than 30 seconds. However, if there is no response for too long, it indicates that the configuration is incorrect.

Firstly, you must speak while holding down your `V` button.

Secondly, this may require writing a console script using the Java+Vosk API to test whether your Java can access the computer's microphone properly, which can be quite cumbersome. Of course, it is generally possible to check if Java has access to the microphone in the privacy or permission settings section of the operating system, see [README.md](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input#q-why-the-program-cannot-to-recognize-the-text-from-the-microphone) or [Fix microphone problems | Microsoft Learn](https://support.microsoft.com/en-us/windows/fix-microphone-problems-5f230348-106d-bfa4-1db5-336f35576011#WindowsVersion=Windows_11).

At present, this module only supports Windows and Linux operating systems, and other operating systems do not yet support it. Please recheck the game and computer configurations, hoping that this can solve your problem.

**Comment by davidthehat** [comment]
I have been playing around with it a bit, using some of your suggestions. I have been able to get it to output something I have said once (just the word test). This confirms for me that the configuration is correct. At the very least, java does have permission to read my microphone and the model is loaded correctly. I am on Windows.

Still, it is very inconsistent. As I said, I've only gotten it to work once despite testing many times. All other times nothing happens besides the little popup that indicates it is "Recording and Recognizing...". I have even checked the logs and see nothing of interest.

Here is a screenshot of my configuration screen. Currently the only things I have modified are the path to the model and the prefix. The default prefix seems to be somewhat unsupported in my font, so I have been messing with it a little bit. The one time I got it to work it was set as [input]. But I doubt this has much to do with my issue.
![image](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/assets/24359213/edd364c2-a165-4a35-8d9a-5ac0f3ed1a72)

I appreciate your assistance so far!

**Comment by davidthehat** [comment]
Oh my. I have figured it out...

I was releasing the button early! With all the talk about being patient and possibly waiting multiple seconds, I expected to have to release the button before it would start recognizing. Instead, I realize now that I have to hold the button until the text sends.

Thanks for you assistance! Have a great day.

**Comment by Jaffe2718** [comment]
Congratulations!

If your computer has sufficient storage space, you can use this [vosk-model-en-us-0.22-lgraph](https://alphacephei.com/vosk/models/vosk-model-en-us-0.22-lgraph.zip) for English models, with a size of 128Mb, which is still reasonable for personal computers and has higher accuracy. Of course, if you want to save computer storage space, choose [vosk-model-small-en-us-0.15](https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip).

Wishing you a pleasant game!😊
