### ISSUE TITLE
Auostic Model Load Failed

### ISSUE THREAD

**Issue by icofs223** [Jaffe2718/Fabric-Microphone-Text-Input#6]
I keep getting this error when it tries to send
![20230626172038_1](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/assets/122234286/bc23ca20-34a4-4f5f-96ba-4661fed816c0)

**Comment by Jaffe2718** [comment]
The acoustic model failed to load because the mod was incorrectly configured, you should read this [tutorial](https://github.com/Jaffe2718/Fabric-Microphone-Text-Input/wiki/Mod-configuration-(Basic)) first. If the problem hasn't been solved, you can provide me your configuration file at `...\.minecraft\versions\YOUR_GAME_CORE\config\mcmti.json`

**Comment by BouncyBonBon** [comment]
I've gone through all the setup and am still struggling with this, even though the config looks fine. Version 1.1.12

[mcmti.json](https://github.com/user-attachments/files/20853673/mcmti.json)

**Comment by Jaffe2718** [comment]
> I've gone through all the setup and am still struggling with this, even though the config looks fine. Version 1.1.12
> 
> [mcmti.json](https://github.com/user-attachments/files/20853673/mcmti.json)

You must set the `acousticModelPath` field with the absolute path of auostic model, for example:
```json
{
  "acousticModelPath": "D:/Software/Minecraft/.minecraft/.mcmti/vosk-model-small-en-us-0.15",
  "cacheSize": 4096,
  "sampleRate": 16000,
  "autoSend": true,
  "prefix": "⌈Speech Input⌋",
  "encodingRepair": true,
  "srcEncoding": "UTF-8",
  "dstEncoding": "UTF-8"
}
```

You need to [download](https://alphacephei.com/vosk/models) and extract the auostic model first, and set the set the `acousticModelPath` field.

**Comment by BouncyBonBon** [comment]
I already did that. It doesn't work - I've since decided to switch to a different mod for this, as I couldn't get it to work.

**Comment by Jaffe2718** [comment]
> I already did that. It doesn't work - I've since decided to switch to a different mod for this, as I couldn't get it to work.

The absolute path you filled in before was indeed wrong.

This is your config file:
```json
{
  "acousticModelPath": "\\vosk-model-en-us-0.22",
  "cacheSize": 4096,
  "sampleRate": 16000,
  "autoSend": true,
  "prefix": "⌈Speech Input⌋",
  "encodingRepair": true,
  "srcEncoding": "UTF-8",
  "dstEncoding": "UTF-8"
}
```

`\\vosk-model-en-us-0.22` cannot be a correct absolute path.

**Comment by BouncyBonBon** [comment]
I mean I already did that earlier. I tried several different paths including the one you sent and it didn't work.

**Comment by Jaffe2718** [comment]
Is it because your OS is Linux? In principle, the libraries for this mod are cross-platform, as long as the paths are correct. Or you can try the `2.x` version of the mod. `2.x` switched to OpenAI's Whisper, which makes it easier to configure the mod and has higher recognition accuracy.
